package pojos;
// Generated Apr 22, 2019 11:53:07 AM by Hibernate Tools 4.3.1



/**
 * DetailTransaction generated by hbm2java
 */
public class DetailTransaction  implements java.io.Serializable {


     private Integer id;
     private Integer idTransaction;
     private Integer idTicket;

    public DetailTransaction() {
    }

    public DetailTransaction(Integer idTransaction, Integer idTicket) {
       this.idTransaction = idTransaction;
       this.idTicket = idTicket;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getIdTransaction() {
        return this.idTransaction;
    }
    
    public void setIdTransaction(Integer idTransaction) {
        this.idTransaction = idTransaction;
    }
    public Integer getIdTicket() {
        return this.idTicket;
    }
    
    public void setIdTicket(Integer idTicket) {
        this.idTicket = idTicket;
    }




}


