package pojos;
// Generated Apr 22, 2019 11:53:07 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Movie generated by hbm2java
 */
public class Movie  implements java.io.Serializable {


     private int id;
     private Integer status;
     private String name;
     private Integer partTime;
     private Integer time;
     private String director;
     private String contain;
     private String trailer;
     private String thumb;
     private String imageUrl;
     private String actor;
     private Integer old;
     private Long view;
     private Integer createBy;
     private Date timeCreate;
     private Integer updateBy;
     private Date timeUpdate;

    public Movie() {
    }

	
    public Movie(int id) {
        this.id = id;
    }
    public Movie(int id, Integer status, String name, Integer partTime, Integer time, String director, String contain, String trailer, String thumb, String imageUrl, String actor, Integer old, Long view, Integer createBy, Date timeCreate, Integer updateBy, Date timeUpdate) {
       this.id = id;
       this.status = status;
       this.name = name;
       this.partTime = partTime;
       this.time = time;
       this.director = director;
       this.contain = contain;
       this.trailer = trailer;
       this.thumb = thumb;
       this.imageUrl = imageUrl;
       this.actor = actor;
       this.old = old;
       this.view = view;
       this.createBy = createBy;
       this.timeCreate = timeCreate;
       this.updateBy = updateBy;
       this.timeUpdate = timeUpdate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getPartTime() {
        return this.partTime;
    }
    
    public void setPartTime(Integer partTime) {
        this.partTime = partTime;
    }
    public Integer getTime() {
        return this.time;
    }
    
    public void setTime(Integer time) {
        this.time = time;
    }
    public String getDirector() {
        return this.director;
    }
    
    public void setDirector(String director) {
        this.director = director;
    }
    public String getContain() {
        return this.contain;
    }
    
    public void setContain(String contain) {
        this.contain = contain;
    }
    public String getTrailer() {
        return this.trailer;
    }
    
    public void setTrailer(String trailer) {
        this.trailer = trailer;
    }
    public String getThumb() {
        return this.thumb;
    }
    
    public void setThumb(String thumb) {
        this.thumb = thumb;
    }
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
    public String getActor() {
        return this.actor;
    }
    
    public void setActor(String actor) {
        this.actor = actor;
    }
    public Integer getOld() {
        return this.old;
    }
    
    public void setOld(Integer old) {
        this.old = old;
    }
    public Long getView() {
        return this.view;
    }
    
    public void setView(Long view) {
        this.view = view;
    }
    public Integer getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }
    public Date getTimeCreate() {
        return this.timeCreate;
    }
    
    public void setTimeCreate(Date timeCreate) {
        this.timeCreate = timeCreate;
    }
    public Integer getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }
    public Date getTimeUpdate() {
        return this.timeUpdate;
    }
    
    public void setTimeUpdate(Date timeUpdate) {
        this.timeUpdate = timeUpdate;
    }




}


