package pojos;
// Generated Apr 22, 2019 11:53:07 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Movietime generated by hbm2java
 */
public class Movietime  implements java.io.Serializable {


     private Integer id;
     private Integer timeStart;
     private Integer dateStart;
     private Integer price;
     private Integer idMovie;
     private Integer idRoom;
     private Integer createBy;
     private Date timeCreate;
     private Integer updateBy;
     private Date timeUpdate;

    public Movietime() {
    }

    public Movietime(Integer timeStart, Integer dateStart, Integer price, Integer idMovie, Integer idRoom, Integer createBy, Date timeCreate, Integer updateBy, Date timeUpdate) {
       this.timeStart = timeStart;
       this.dateStart = dateStart;
       this.price = price;
       this.idMovie = idMovie;
       this.idRoom = idRoom;
       this.createBy = createBy;
       this.timeCreate = timeCreate;
       this.updateBy = updateBy;
       this.timeUpdate = timeUpdate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getTimeStart() {
        return this.timeStart;
    }
    
    public void setTimeStart(Integer timeStart) {
        this.timeStart = timeStart;
    }
    public Integer getDateStart() {
        return this.dateStart;
    }
    
    public void setDateStart(Integer dateStart) {
        this.dateStart = dateStart;
    }
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }
    public Integer getIdMovie() {
        return this.idMovie;
    }
    
    public void setIdMovie(Integer idMovie) {
        this.idMovie = idMovie;
    }
    public Integer getIdRoom() {
        return this.idRoom;
    }
    
    public void setIdRoom(Integer idRoom) {
        this.idRoom = idRoom;
    }
    public Integer getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }
    public Date getTimeCreate() {
        return this.timeCreate;
    }
    
    public void setTimeCreate(Date timeCreate) {
        this.timeCreate = timeCreate;
    }
    public Integer getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }
    public Date getTimeUpdate() {
        return this.timeUpdate;
    }
    
    public void setTimeUpdate(Date timeUpdate) {
        this.timeUpdate = timeUpdate;
    }




}


