package pojos;
// Generated Apr 22, 2019 11:53:07 AM by Hibernate Tools 4.3.1



/**
 * Moviecategory generated by hbm2java
 */
public class Moviecategory  implements java.io.Serializable {


     private int id;
     private Integer idCategory;
     private Integer idMovie;

    public Moviecategory() {
    }

	
    public Moviecategory(int id) {
        this.id = id;
    }
    public Moviecategory(int id, Integer idCategory, Integer idMovie) {
       this.id = id;
       this.idCategory = idCategory;
       this.idMovie = idMovie;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getIdCategory() {
        return this.idCategory;
    }
    
    public void setIdCategory(Integer idCategory) {
        this.idCategory = idCategory;
    }
    public Integer getIdMovie() {
        return this.idMovie;
    }
    
    public void setIdMovie(Integer idMovie) {
        this.idMovie = idMovie;
    }




}


