package pojos;
// Generated Apr 22, 2019 11:53:07 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ticket generated by hbm2java
 */
public class Ticket  implements java.io.Serializable {


     private Integer idTicket;
     private Integer status;
     private Integer price;
     private Integer idMovietime;
     private Integer idZoomDetail;
     private Integer createBy;
     private Date timeCreate;
     private Integer updateBy;
     private Date timeUpdate;

    public Ticket() {
    }

    public Ticket(Integer status, Integer price, Integer idMovietime, Integer idZoomDetail, Integer createBy, Date timeCreate, Integer updateBy, Date timeUpdate) {
       this.status = status;
       this.price = price;
       this.idMovietime = idMovietime;
       this.idZoomDetail = idZoomDetail;
       this.createBy = createBy;
       this.timeCreate = timeCreate;
       this.updateBy = updateBy;
       this.timeUpdate = timeUpdate;
    }
   
    public Integer getIdTicket() {
        return this.idTicket;
    }
    
    public void setIdTicket(Integer idTicket) {
        this.idTicket = idTicket;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }
    public Integer getIdMovietime() {
        return this.idMovietime;
    }
    
    public void setIdMovietime(Integer idMovietime) {
        this.idMovietime = idMovietime;
    }
    public Integer getIdZoomDetail() {
        return this.idZoomDetail;
    }
    
    public void setIdZoomDetail(Integer idZoomDetail) {
        this.idZoomDetail = idZoomDetail;
    }
    public Integer getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }
    public Date getTimeCreate() {
        return this.timeCreate;
    }
    
    public void setTimeCreate(Date timeCreate) {
        this.timeCreate = timeCreate;
    }
    public Integer getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }
    public Date getTimeUpdate() {
        return this.timeUpdate;
    }
    
    public void setTimeUpdate(Date timeUpdate) {
        this.timeUpdate = timeUpdate;
    }




}


