package pojos;
// Generated Apr 22, 2019 11:53:07 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UserAdmin generated by hbm2java
 */
public class UserAdmin  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private String displayName;
     private String lastName;
     private String name;
     private Integer role;
     private Date lastLogin;
     private String token;
     private Integer creatBy;
     private Date createTime;
     private Integer updateBy;
     private Date updateTime;

    public UserAdmin() {
    }

    public UserAdmin(String username, String password, String displayName, String lastName, String name, Integer role, Date lastLogin, String token, Integer creatBy, Date createTime, Integer updateBy, Date updateTime) {
       this.username = username;
       this.password = password;
       this.displayName = displayName;
       this.lastName = lastName;
       this.name = name;
       this.role = role;
       this.lastLogin = lastLogin;
       this.token = token;
       this.creatBy = creatBy;
       this.createTime = createTime;
       this.updateBy = updateBy;
       this.updateTime = updateTime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getRole() {
        return this.role;
    }
    
    public void setRole(Integer role) {
        this.role = role;
    }
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public Integer getCreatBy() {
        return this.creatBy;
    }
    
    public void setCreatBy(Integer creatBy) {
        this.creatBy = creatBy;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public Integer getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }




}


