package pojos;
// Generated Apr 22, 2019 11:53:07 AM by Hibernate Tools 4.3.1



/**
 * ZoomDetail generated by hbm2java
 */
public class ZoomDetail  implements java.io.Serializable {


     private Integer id;
     private Integer row;
     private Integer col;
     private Integer type;
     private Integer postion;
     private Integer room;

    public ZoomDetail() {
    }

    public ZoomDetail(Integer row, Integer col, Integer type, Integer postion, Integer room) {
       this.row = row;
       this.col = col;
       this.type = type;
       this.postion = postion;
       this.room = room;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getRow() {
        return this.row;
    }
    
    public void setRow(Integer row) {
        this.row = row;
    }
    public Integer getCol() {
        return this.col;
    }
    
    public void setCol(Integer col) {
        this.col = col;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public Integer getPostion() {
        return this.postion;
    }
    
    public void setPostion(Integer postion) {
        this.postion = postion;
    }
    public Integer getRoom() {
        return this.room;
    }
    
    public void setRoom(Integer room) {
        this.room = room;
    }




}


